# Generated by Django 4.0.5 on 2022-06-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("steamapp_id", models.IntegerField()),
                ("name", models.TextField()),
                ("thumbnail", models.TextField()),
                ("cheapest_deal_id", models.TextField(blank=True, default="")),
                ("cheapest_deal_price", models.FloatField(null=True)),
            ],
        ),
    ]
